Repository Joy-of-Coding/ReactJam_Fall_2024, pull requests merged in 2024-10, with the labels that each got.

#35 Tbatch css
  JamCrawler/src/assets/grit.png
  JamCrawler/src/components/Game.css
  JamCrawler/src/components/Game.tsx
  JamCrawler/src/components/Inventory.css
  JamCrawler/src/components/Inventory.tsx
  JamCrawler/src/components/TodoList.css
Labels: ready for merge

#47 Update stats labels and alignments
  JamCrawler/src/components/Game.tsx
  JamCrawler/src/components/MonsterStats.css
  JamCrawler/src/components/MonsterStats.tsx
  JamCrawler/src/components/PlayerStats.css
  JamCrawler/src/components/PlayerStats.tsx
  JamCrawler/src/types/types.ts
Labels: draft

#50 Anna branch
  JamCrawler/src/components/MonsterStats.css
  JamCrawler/src/components/MonsterStats.tsx
  JamCrawler/src/components/PlayerStats.css
  JamCrawler/src/components/PlayerStats.tsx
Labels: ready for merge

#90 Monster Update: PLEASE READ COMMENT HERE on dungeon map not showing, but it's there just invisible. C…
  JamCrawler/src/components/Combat/CombatEncounter.tsx
  JamCrawler/src/components/Combat/player_monster_level_constants.ts
  JamCrawler/src/components/Dungeon.tsx
  JamCrawler/src/components/Game.tsx
  JamCrawler/src/types/types.ts
Labels: help wanted
